packages:
  - apps/*
  - packages/*
  - video

allowBuilds:
  '@google/genai': false
  electron: false
  electron-winstaller: false
  esbuild: false
  node-pty: false
  protobufjs: false
  sharp: false
